.TH "tcpmt" "1" "0.93.beta" "Gilles Berger Sabbatel" "User Manual"
.SH "NAME"
.LP 
tcpmt \-  TCP measurement tool, part of the ipmt tools suite
.SH "SYNTAX"
.LP 
tcpmt [\fIoptions\fP] <\fIhost\fP>
.LP 
tcpmt -P [\fIoptions\fP]
.SH "DESCRIPTION"
.LP 
Tcpmt is the client program which send flows 
of data to the server program (tcptarget) with the TCP protocol.
.SH "OPTIONS"
.LP 
.TP 
\fB\-p\fR <\fIport\fP>
Port number to use.  The default is to use port number 13000.
.TP 
\fB\-s\fR <\fIpktsz\fP>
Size of packets to send in bytes.  The default size is 1460 bytes in IPv4,
and 1452 bytes in IPv6.
.TP 
\fB\-d\fR <\fIsecs\fP>
Test duration in seconds.  By default, the program transmits untils stopped by the user.
.TP
\fB\-n\fR <\fIdatasz\fP>
Number of bytes to send. By default, the program transmits untils stopped by the user.
.TP 
\fB\-N\fR <\fIpktnb\fP>
Number of packets to send.  By default, the program transmits untils stopped by the user.
.TP
\fB\-P\fR
passive - Connection establishment will come from tcptarget -A; this is the only case where
the host argument is not used.
.TP 
\fB\-S\fR <\fIport\fP>
Specify source port.
.TP 
\fB\-4\fR
Force IPv4 protocol.  The default is tu use IPv6 if supported, else fallback
to IPv4.
.TP 
\fB\-6\fR
Force IPv6 protocol if supported.  Unlike the default case, the program 
fails if IPv6 is not supported, rather than fallback to IPv4.
.TP 
\fB\-t\fR
Starts a traffic sink that will eat the data received on the socket. Bidirectional traffic can be generated by starting "tcpmt -t -P" on one side and "tcpmt -t <hostname>" on the other.
.TP 
\fB\-f\fR <\fItest-file.txt\fP>
Reads traffic description from test-file.txt. Basically, the file describes single transfers: [11.1 12 13] waits  11.1 ms, then opens a connection and writes 12 times 13 bytes into it. Loops are also possible: {10.1 20 [11.1 12 13]} waits 10.1 ms, then repeats 20 times the previous transfer (including the 11.1 ms initial wait). Nested repetitions are possible: {100 200 {10 20 [11 12 1300]}} waits 100+10+11ms (this happens only once), then writes 240 times 1300 bytes into 20 connections, waits 10+11 ms, writes.. etc. A repetition number of -1 (e.g. {0 -1 [...]}) loops for ever.
.TP 
\fB\-h\fR
Output help information and exit.
.TP 
\fB\-v\fR
Output version information and exit.
.SH "EXAMPLES"
.LP 
The following command continuously send packets to the port 10000 of the host
destination :
.LP 
tcpmt \-p 10000 destination
.SH "AUTHORS"
.LP 
Gilles Berger Sabbatel <Gilles.B erger\-Sabbatel@imag.fr>
.SH "SEE ALSO"
.LP 
udptarget(1), udpmt(1), tcptarget(1)
